# Generated by Django 5.1 on 2025-06-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_home_header_remove_home_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
