# Generated by Django 5.2 on 2025-06-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=264)),
                ('header', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='Features')),
                ('image2', models.ImageField(upload_to='Features')),
                ('image3', models.ImageField(upload_to='Features')),
                ('text1', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=100)),
                ('text3', models.CharField(max_length=100)),
            ],
        ),
    ]
