# Generated by Django 5.2 on 2025-06-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='header2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
