# Generated by Django 5.2 on 2025-06-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_features_header2'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='description2',
            field=models.TextField(default=0, max_length=264),
            preserve_default=False,
        ),
    ]
