# Generated by Django 5.2 on 2025-06-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_features_description2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='CTA')),
            ],
        ),
    ]
