# Generated by Django 5.2 on 2025-06-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='title',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
